// Generated by Xata Codegen 0.29.2. Please do not edit.
import { buildClient } from "@xata.io/client";
/** @typedef { import('./types').SchemaTables } SchemaTables */
/** @type { SchemaTables } */
const tables = [
  {
    name: "db_clientes",
    columns: [
      { name: "CLIENTE", type: "string" },
      { name: "COD", type: "int" },
      { name: "CIDADE", type: "string" },
    ],
    revLinks: [{ column: "link", table: "Pedidos" }],
  },
  {
    name: "products",
    columns: [
      {
        name: "product_name",
        type: "string",
        notNull: true,
        defaultValue: "null",
      },
      { name: "img", type: "file", file: { defaultPublicAccess: true } },
    ],
  },
  {
    name: "Pedidos",
    columns: [
      { name: "Data", type: "datetime", defaultValue: "now" },
      { name: "link", type: "link", link: { table: "db_clientes" } },
      { name: "cod_vendedor", type: "int", defaultValue: "0" },
      { name: "tipo_pgt", type: "bool", notNull: true, defaultValue: "true" },
      { name: "nf", type: "bool", notNull: true, defaultValue: "true" },
      {
        name: "produtos",
        type: "json",
        notNull: true,
        defaultValue: "[\n  {}\n]",
      },
    ],
  },
];
/** @type { import('@xata.io/client').ClientConstructor<{}> } */
const DatabaseClient = buildClient();
const defaultOptions = {
  databaseURL:
    "https://crokids-s-workspace-iltlld.us-west-2.xata.sh/db/digel-db",
};
/** @typedef { import('./types').DatabaseSchema } DatabaseSchema */
/** @extends DatabaseClient<DatabaseSchema> */
export class XataClient extends DatabaseClient {
  constructor(options) {
    super({ ...defaultOptions, ...options }, tables);
  }
}
let instance = undefined;
/** @type { () => XataClient } */
export const getXataClient = () => {
  if (instance) return instance;
  instance = new XataClient();
  return instance;
};
